tests: add check for dulwich in test-url-parsing.py
Previously, if dulwich wasn't available, this test would fail with a traceback
(example included below).  This changeset makes it so that the test will be
skipped with an informative message if dulwich isn't available.

Traceback (most recent call last):
  File "/Users/carrd/hg-repos/hg-git-queue/tests/test-url-parsing.py", line 6, in <module>
    from hggit.git_handler import GitHandler
  File "/Users/carrd/hg-repos/hg-git-queue/tests/../hggit/__init__.py", line 42, in <module>
    import gitrepo, hgrepo
  File "/Users/carrd/hg-repos/hg-git-queue/tests/../hggit/gitrepo.py", line 13, in <module>
    from git_handler import GitHandler
  File "/Users/carrd/hg-repos/hg-git-queue/tests/../hggit/git_handler.py", line 4, in <module>
    from dulwich.errors import HangupException, GitProtocolError, UpdateRefsError
ImportError: No module named dulwich.errors